apiVersion: v2
appVersion: 1.21.1
dependencies:
- name: gitea
  repository: https://dl.gitea.io/charts 
  version: 12.4.0
description: Gitea Helm chart for Kubernetes
icon: https://docs.gitea.io/images/gitea.png
name: gitea-umbrella
sources:
- https://gitea.com/gitea/helm-chart
- https://github.com/go-gitea/gitea
- https://hub.docker.com/r/gitea/gitea/
type: application
version: 2.0
