apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itobey/k3s-nuc.git
    targetRevision: HEAD
    path: deploy/paperless
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

