kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: zwave
  name: pvc-zwave
spec:
  storageClassName: zwave-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
