kind: PersistentVolume
apiVersion: v1
metadata:
  name: zwave-pv
  namespace: zwave
spec:
  storageClassName: zwave-manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/enc/docker-volumes/zwave"
