apiVersion: v1
kind: Service
metadata:
  name: zwave-svc
  namespace: zwave
spec:
  selector:
    app: zwave
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: websocket
      port: 3000
      targetPort: websocket
  externalTrafficPolicy: Local
  type: LoadBalancer