apiVersion: v1
kind: Service
metadata:
  name: zwave-svc
  namespace: zwave
  labels:
    app: zwave
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: websocket
      port: 3000
      targetPort: websocket
  selector:
    app: zwave
  type: LoadBalancer