apiVersion: v1
kind: Service
metadata:
  name: zwave
  namespace: zwave
  labels:
    name: zwave
spec:
  ports:
    - name: websocket
      port: 3000
      targetPort: 3000
    - name: http
      port: 8091
      targetPort: 8091
  selector:
    name: zwave
  type: LoadBalancer