apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
  labels:
    app: paperless
spec:
  ports:
    - port: 8000
  selector:
    app: paperless
    tier: frontend
  type: ClusterIP