apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secret
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_DBPASS: AgASCsPGIDFnTIo9xO+5rx2IJPrqfEL4gJsFn69kcPn7UkX6iEIcbHa7L7n/D7jTaIYSh0cSfjKr3IStJtzhp2GcZzC1dcQGEJ5xN1QT9XIWsYeewugepVziPnflnajnGTKDe8/jCh0pnfwKcgRNd+AYFK+WNBoiziLZf9eDwXbJLUFbUgN3+7i9N9RKvpsmUWJ2sS8VPplieAkGK77DR6G+vEX9qhzG8+QGzVLJHVOv7uVw0DrNqNaseMHXQEuVdFKSR/npZa/t1LeRVzcUS1YoUqAKwYzP23lYQZfBnjnpFNcJjoW/PVceBL4GFlN3pSRCPkSbmStSQRKxtIZSU2AJ/yNs8V3rTKM6d/gVqv/3jN+Ig3ll3Q1k+gSmBQBjVDod1pRQ+oAp3y6t2GsTgr2HZnofucZaramEs9lSWvwZZDl8b4C310L+XcFc14NddoIYhfUYen7CktxTwiScveEIXGddi704czwcZD3UJRMSSbvxuD7a9DgXvp5bChVbHUieEE30uNOUZxWewo8zyGSqzpU6NaarzW7RE25goQ7nZA6VkykTM+cMe5PC+93a51DTC11uYS0vys5e3xAKfixt6QsinhP4YCK8hbzFJqH84LWSNrnhGfkGtiCn/sz/Hci8Mgw8aQ97uslo81clI6ct2QJd/MNBU+sme+IH3LaRHBXs0/rHA6J+oU6weUrmz5neh8lxpWaRUsRKp9A=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-secret
      namespace: paperless
    type: Opaque