apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: paperless-pv
  resources:
    requests:
      storage: 100Gi
