apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-input-pv
  labels:
    type: local
spec:
  storageClassName: paperless-pv
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/resilio-data/folders/tobi_handy_sync_folder/_paperless-input"
